version: '3.9'

services:
  telegram-news-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-news-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION_NAME=${SESSION_NAME}
      - WEBHOOK_URL=${WEBHOOK_URL}
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "http://host.docker.internal:5678"
    depends_on:
      - n8n
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API и веб-интерфейс
      - "6334:6334"  # gRPC порт
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


